on:
  push:
    branches:
      main
jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: deploy
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.2
        - name: Deploy files
          #uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          uses: SamKirkland/FTP-Deploy-Action@4.0.0
          with:
            username: ${{ secrets.STAQQ_DEV_FTP_USERNAME }}
            password: ${{ secrets.STAQQ_DEV_FTP_PASSWORD }}
            server: ${{ secrets.STAQQ_DEV_FTP_HOST }}
            port: '21'
            server-dir: '/'
